[package]
name = "cve-webhook"
version = "0.2.0"
authors = ["Roland Mueller"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls", "cookies"] }
tokio = { version = "1.25", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_yaml = "0.9"
serde_json = "1.0"
tera = "1.17"
futures = "0.3"
structopt = "0.3"